name: Publish NPM packages

on:
  pull_request:
  workflow_dispatch:
    inputs:
      confirmation:
        description: I have seen the latest CI results for this branch
        type: boolean
        default: false
        required: true
      dry-run:
        description: Dry run (for testing)
        type: boolean
        default: false
        required: true

jobs:
  publish:
    name: Publish
    # if: ${{ github.event.inputs.confirmation }}
    runs-on: ubuntu-20.04
    steps:
      - run: echo "https://registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        name: Configure NPM token

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - run: yarn install

      - run: yarn exe scripts/packages/publish-to-npmjscom.ts
        env:
          # DRY_RUN: ${{ github.event.inputs.dry-run }}
          DRY_RUN: ${{ "true" }}
