name: Site deployment

on:
  deployment_status:
  schedule:
    - cron: "*/10 * * * *" ## Every 10 minutes
    - cron: "0 4 * * *" ## Every night (UTC time)

jobs:
  warm_up_vercel:
    ## Vercel uses AWS Lambda. When we call getStaticProps in fallback mode or getServerSideProps,
    ## a cold Lambda function may take 5-15 seconds to execute. This pipeline warms up Lambda
    ## containers for new deployments and keeps them up by fetching affected URLs every 10 minutes.
    ## Context: https://github.com/orgs/vercel/discussions/496
    name: Warm up Vercel
    if: github.event_name == 'schedule' || github.event.deployment_status.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch URLs that use AWS Lambda
        run: |
          cat << EOF > curl-format.txt
            %{url_effective}\n
              Status code: %{response_code}\n
              Time: %{time_total}\n
            \n
          EOF

          for PATHNAME in "/@hash" "/@hash/blocks/divider/sandboxed-demo" "/api/me" "/types/DUMMY_ENTITY_ID"; do
            npx retry-cli@0.6.0 -- curl --output /dev/null --silent --write-out "@curl-format.txt" "${BASE_URL}${PATHNAME}"
          done
        env:
          BASE_URL: ${{ github.event.deployment.environment != 'production' && github.event.deployment_status.target_url || 'https://blockprotocol.org' }}
          NODE_OPTIONS: --no-deprecation ## https://github.com/tirsen/retry-cli/issues/7

  smoke_tests:
    name: Smoke tests
    if: github.event.schedule == '0 4 * * *' || github.event.deployment_status.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn install

      - run: yarn playwright install-deps chrome
        if: ${{ success() || failure() }}

      - name: Run Playwright tests
        if: ${{ success() || failure() }}
        run: |
          yarn workspace @blockprotocol/site playwright test --project=smoke
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
